version: "3.8"
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: workforce
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo123
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  app:
    build: .
    environment:
      DB_USER: demo
      DB_PASSWORD: demo123
      DB_NAME: workforce
      DB_HOST: mysql
    working_dir: /app
    depends_on:
      - mysql
    stdin_open: true
    tty: true